version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      -./config/.env

  volumes:
    postgres_data:


  django:
    build: ./02_django_api
    depends_on:
      - db
    env_file:
      -./config/.env
    volumes:
      - static:/02_django_api/static
      - media:/02_django_api/media
      - nginx_conf:/02_django_api/nginx/

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static:/02_django_api/static
      - media:/02_django_api/media
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
    depends_on:
      - django
    restart: always

  elastic:
    env_file:
      - ./.env
    image: docker.io/elastic/elasticsearch:8.1.0
    volumes:
      - ./elasticsearch/elasticsearch.yml:/var/lib/elasticsearch/elasticsearch.yml
    environment:
      discovery: type=single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
    expose:
      - "9200"
